
DOMAIN_ROUTE = 'domains'
LAYER_ROUTE = 'layers'
PROVIDER_ROUTE = 'database-providers'
DATABASE_ROUTE = 'databases'
SCHEMA_ROUTE = 'schemas'
TABLE_ROUTE = 'tables'
F_Q_NAME_ROUTE = "fqn"
CONNECTION_ROUTE = "connections"
INGESTION_ROUTE = "ingestions"

SQLTYPES_DICT = {
    'VARBINARY' : 'BINARY',
    'DATE' : 'DATE',
    'BIG_INTEGER' : 'BIGINT',
    'BLOB' : 'BLOB',
    'CHAR' : 'CHAR',
    'DECIMAL' : 'DECIMAL',
    'ARRAY' : 'ARRAY',
    'BIGINT' : 'BIGINT',
    'STRING' : 'STRING',
    'REAL' : 'FLOAT',
    'DATETIME' : 'DATETIME',
    'VARCHAR' : 'VARCHAR',
    'TIMESTAMP' : 'TIMESTAMP',
    'NULL' : 'NULL',
    'JSON' : 'JSON',
    'BINARY' : 'BINARY',
    'ENUM' : 'ENUM',
    'INTEGER' : 'INT',
    'BOOLEAN' : 'BOOLEAN',
    'SMALLINT' : 'SMALLINT',
    'NUMERIC' : 'NUMERIC',
    'SMALL_INTEGER' : 'SMALLINT',
    'TIME' : 'TIME',
    'CLOB' : 'CLOB',
    'FLOAT' : 'FLOAT',
    'TEXT' : 'TEXT',
    'LARGE_BINARY' : 'BINARY',
}
