### Tests for entity AIModel API ###
@path = ai-models

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "André Rocha" , 
    "fully_qualified_name": "db-91.pires.com" , 
    "display_name": "Ravy Fonseca" , 
    "description": "Neque quibusdam nemo sit." , 
    "notes": "Vel officiis facere dolorem tenetur." , 
    "deleted": false , 
    "version": "678.38.29" , 
    "updated_at": "2025-02-05T18:54:12.159198" , 
    "updated_by": "tester" , 
    "type": "type" , 
    "algorithms": "algorithms" , 
    "technologies": "technologies" , 
    "server": "server" , 
    "source": "source" , 
    "domain_id": "domain" , 
    "layer_id": "layer" , 

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Olívia Barros" , 
    "fully_qualified_name": "desktop-77.moura.com" , 
    "display_name": "Dra. Heloisa Pacheco" , 
    "description": "Ab libero quibusdam magni." , 
    "notes": "Hic repudiandae ducimus cumque." , 
    "deleted": true , 
    "version": "389.63.32" , 
    "updated_at": "2025-01-02T17:07:33.782996" , 
    "updated_by": "tester" , 
    "type": "type" , 
    "algorithms": "algorithms" , 
    "technologies": "technologies" , 
    "server": "server" , 
    "source": "source" , 
    "domain_id": "domain" , 
    "layer_id": "layer" , 
}
