### Tests for entity DatabaseProvider API ###
@path = database-providers

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "Servidor01" ,
    "fully_qualified_name": "web-82.garcia.biz" ,
    "display_name": "Servidor01" ,
    "description": "Challenge manager data how." ,
    "notes": "Gun former good enjoy." ,
    "deleted": true ,
    "version": "83.5.24" ,
    "updated_at": "2025-02-21T10:46:30.268860" ,
    "updated_by": "tester" ,
    "configuration": "configuration" ,
    "domain_id": "94ff50a3-ff9e-409b-b111-a86b77e4f91b" ,
    "layer_id": "930448ee-954c-40ad-b498-3d0fbe299fa6" ,
    "provider_type_id": "POSTGRESQL"

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}

DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
@fqn = {{list.response.body.items.$[0].fully_qualified_name}}
GET {{host}}/{{path}}/{{fqn}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Servidor01.uucp" ,
    "fully_qualified_name": "servidor01.garcia.uucp" ,
    "display_name": "Servidor01" ,
    "description": "Challenge manager data how." ,
    "notes": "Gun former good enjoy." ,
    "deleted": true ,
    "version": "83.5.24" ,
    "updated_at": "2025-02-21T10:46:30.268860" ,
    "updated_by": "tester" ,
    "configuration": "configuration" ,
    "domain_id": "94ff50a3-ff9e-409b-b111-a86b77e4f91b"
}
###
PATCH {{host}}/{{path}}/{{fqn}}

{
    "name": "Servidor01.uucp" ,
    "fully_qualified_name": "servidor01.garcia.uucp" ,
    "display_name": "Servidor01" ,
    "description": "Challenge manager data how. With FQN" ,
    "notes": "Gun former good enjoy." ,
    "deleted": true ,
    "version": "83.5.24" ,
    "updated_at": "2025-02-21T10:46:30.268860" ,
    "updated_by": "tester" ,
    "configuration": "configuration"
}
