### Tests for entity DatabaseSchema API ###
@path = schemas

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "public" ,
    "fully_qualified_name": "public.gutierrez.net" ,
    "display_name": "Public" ,
    "description": "The word during father per." ,
    "notes": "Water sit key ten better bill." ,
    "deleted": false ,
    "version": "528.7.9" ,
    "updated_at": "2025-02-07T07:30:43.279739" ,
    "updated_by": "tester" ,
    "database_id": "d485c47a-65d1-4523-813e-7e488f2f5c50"

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Public" ,
    "fully_qualified_name": "web-75.lopez-mccoy.com" ,
    "display_name": "Public" ,
    "description": "From laugh many probably." ,
    "notes": "Particular west require in." ,
    "deleted": false ,
    "version": "7.41.5" ,
    "updated_at": "2025-02-02T21:16:52.802601" ,
    "updated_by": "tester" ,
    "domain_id": "domain" ,
    "layer_id": "layer" ,
    "database_id": "database"
}
