### Tests for entity DatabaseProviderIngestion API ###
@path = ingestions

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "Ingestão de dados" ,
    "deleted": false ,
    "type": "ingestion" ,
    "include_database": ".+" ,
    "exclude_database": "" ,
    "include_schema": ".+" ,
    "exclude_schema": "" ,
    "include_table": ".+" ,
    "exclude_table": "" ,
    "include_view": true,
    "override_mode": "override" ,
    "scheduling": "{}" ,
    "recent_runs_statuses": "ERROR" ,
    "retries": 5 ,
    "provider_id": "2dc97fdc-7086-404a-90b9-1ab285f7645d"
}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Ingestão de dados principais" ,
    "deleted": false ,
    "type": "ingestion" ,
    "include_database": ".+" ,
    "exclude_database": "" ,
    "include_schema": ".+" ,
    "exclude_schema": "tmp" ,
    "include_table": ".+" ,
    "exclude_table": "" ,
    "include_view": true,
    "override_mode": "override" ,
    "scheduling": "{}" ,
    "recent_runs_statuses": "ERROR" ,
    "retries": 5 ,
    "provider_id": "2dc97fdc-7086-404a-90b9-1ab285f7645d"
}
