### Tests for entity Database API ###
@path = databases

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "Oliver Moreira" ,
    "fully_qualified_name": "lt-95.costela.br" ,
    "display_name": "Anna Liz Vieira" ,
    "description": "Modi hic veniam deleniti." ,
    "notes": "Aperiam accusamus in." ,
    "deleted": true ,
    "version": "15.1.7" ,
    "updated_at": "2025-02-09T01:42:47.694268" ,
    "updated_by": "tester" ,
    "retention_period": "retention_period" ,
    "domain_id": "domain" ,
    "layer_id": "layer" ,
    "provider_id": "provider"

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

### Does not exists
GET {{host}}/{{path}}/d485c47a-ffff-ffff-813e-7e488f2f5c50


###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Lara Silveira" ,
    "fully_qualified_name": "db-48.vasconcelos.br" ,
    "display_name": "Theodoro da Cunha" ,
    "description": "Eius officia assumenda ad." ,
    "notes": "Mollitia nisi nesciunt maiores." ,
    "deleted": false ,
    "version": "714.572.307" ,
    "updated_at": "2025-03-06T00:53:40.089592" ,
    "updated_by": "tester" ,
    "retention_period": "retention_period" ,
    "domain_id": "domain" ,
    "layer_id": "layer" ,
    "provider_id": "provider"
}
