### Tests for entity DatabaseTableSample API ###
@path = samples

###
POST {{host}}/{{path}} HTTP/1.1

{
    "date": "date" , 
    "content": "content" , 
    "is_visible": "is_visible" , 
    "database_table_id": "database_table" 

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "date": "date" , 
    "content": "content" , 
    "is_visible": "is_visible" , 
    "database_table_id": "database_table" 
}
