### Tests for entity Domain API ###
@path = domains

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "Company" ,
    "description": "Company Domain" ,
    "deleted": false
}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Gabinete de Segurança Institucional" ,
    "description": "GSI." ,
    "deleted": false
}
