### Tests for entity ResponsibilityType API ###
@path = responsibility-types

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Isaac Sousa" ,
    "description": "Eos porro optio nam ut dicta." ,
    "deleted": true
}
