### Tests for entity Tag API ###
@path = tags

###
POST {{host}}/{{path}} HTTP/1.1

{
    "name": "Bruna Guerra" , 
    "deleted": false , 
    "description": "At beatae delectus provident." , 
    "applicable_to": "applicable_to" 

}

###
# @name list
GET {{host}}/{{path}}

###
@id = {{list.response.body.items.$[0].id}}
DELETE {{host}}/{{path}}/{{id}}

###
GET {{host}}/{{path}}/{{id}}

###
PATCH {{host}}/{{path}}/{{id}}

{
    "name": "Sr. Thales Pereira" , 
    "deleted": true , 
    "description": "Sapiente culpa rerum ipsum." , 
    "applicable_to": "applicable_to" 
}
