"""search optimization

Revision ID: 04349a255f76
Revises: 91dccfefd405
Create Date: 2025-03-27 13:46:53.032398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04349a255f76'
down_revision: Union[str, None] = '91dccfefd405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_asset', sa.Column('tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tb_asset', sa.Column('search', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_search_search', 'tb_asset', ['search'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_search', table_name='tb_asset', postgresql_using='gin')
    op.drop_column('tb_asset', 'search')
    op.drop_column('tb_asset', 'tree')
    # ### end Alembic commands ###
