"""change scheduling type

Revision ID: 101ed9a4395d
Revises: 9298cefbb831
Create Date: 2025-05-17 04:54:13.457399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '101ed9a4395d'
down_revision: Union[str, None] = '9298cefbb831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_database_provider_ingestion', 'scheduling',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('tb_database_provider_ingestion', 'scheduling_type',
               existing_type=postgresql.ENUM('MANUAL', 'CRON', name='SchedulingTypeEnumType'),
               nullable=True,
               existing_server_default=sa.text('\'MANUAL\'::"SchedulingTypeEnumType"'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_database_provider_ingestion', 'scheduling_type',
               existing_type=postgresql.ENUM('MANUAL', 'CRON', name='SchedulingTypeEnumType'),
               nullable=False,
               existing_server_default=sa.text('\'MANUAL\'::"SchedulingTypeEnumType"'))
    op.alter_column('tb_database_provider_ingestion', 'scheduling',
               existing_type=sa.String(length=200),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###