"""add more provider types

Revision ID: 22eded041a40
Revises: 04349a255f76
Create Date: 2025-03-28 13:04:10.087497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import ResponsibilityType, DatabaseProviderType
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = '22eded041a40'
down_revision: Union[str, None] = '04349a255f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    session.add_all(
        [
            DatabaseProviderType(
                id="HDFS",
                display_name="Apache HDFS",
                image="hdfs",
                supports_schema=False,
            ),
            DatabaseProviderType(
                id="ICEBERG",
                display_name="Apache Iceberg",
                image="iceberg",
                supports_schema=False,
            ),
        ]
    )

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    (
        session.query(DatabaseProviderType)
        .filter(
            DatabaseProviderType.id.in_(
                [
                    "HDFS",
                    "ICEBERG",
                ]
            )
        )
        .delete(synchronize_session=False)
    )
   
    # ### end Alembic commands ###
