"""add columns

Revision ID: 342d16d3bbe5
Revises: f7631ccc6a29
Create Date: 2025-03-23 13:42:05.059293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342d16d3bbe5'
down_revision: Union[str, None] = 'f7631ccc6a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_table_column', sa.Column('semantic_type', sa.String(length=200), nullable=True))
    op.add_column('tb_table_column', sa.Column('default_value', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_table_column', 'default_value')
    op.drop_column('tb_table_column', 'semantic_type')
    # ### end Alembic commands ###
