"""add new columns to ingestion for sampling and semantic type

Revision ID: a0e748bf1825
Revises: 101ed9a4395d
Create Date: 2025-05-28 22:27:35.987456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a0e748bf1825"
down_revision: Union[str, None] = "101ed9a4395d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_database_provider_ingestion",
        sa.Column(
            "collect_sample",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "tb_database_provider_ingestion",
        sa.Column(
            "apply_semantic_analysis",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_database_provider_ingestion", "apply_semantic_analysis")
    op.drop_column("tb_database_provider_ingestion", "collect_sample")
    # ### end Alembic commands ###
