"""Unique

Revision ID: ceca30ce6e89
Revises: d78983e7e563
Create Date: 2025-02-28 20:31:38.153985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceca30ce6e89'
down_revision: Union[str, None] = 'd78983e7e563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inx_uq_asset', 'tb_asset', type_='unique')
    op.create_unique_constraint('inx_uq_asset', 'tb_asset', ['fully_qualified_name', 'asset_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inx_uq_asset', 'tb_asset', type_='unique')
    op.create_unique_constraint('inx_uq_asset', 'tb_asset', ['fully_qualified_name'])
    # ### end Alembic commands ###
