"""add_ingestion_execution

Revision ID: f4912149588a
Revises: 22eded041a40
Create Date: 2025-04-09 16:30:32.562617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4912149588a'
down_revision: Union[str, None] = '22eded041a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_database_provider_ingestion_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('trigger_mode', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('ingestion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['tb_database_provider_ingestion.id'], name='fk_database_provider_ingestion_execution_ingestion_id'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['tb_user.id'], name='fk_database_provider_ingestion_execution_triggered_by_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_database_provider_ingestion_execution_ingestion_id'), 'tb_database_provider_ingestion_execution', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_tb_database_provider_ingestion_execution_triggered_by_id'), 'tb_database_provider_ingestion_execution', ['triggered_by_id'], unique=False)
    op.add_column('tb_database_provider_ingestion_log', sa.Column('execution_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tb_database_provider_ingestion_log_execution_id'), 'tb_database_provider_ingestion_log', ['execution_id'], unique=False)
    op.create_foreign_key('fk_database_provider_ingestion_log_execution_id', 'tb_database_provider_ingestion_log', 'tb_database_provider_ingestion_execution', ['execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_database_provider_ingestion_log_execution_id', 'tb_database_provider_ingestion_log', type_='foreignkey')
    op.drop_index(op.f('ix_tb_database_provider_ingestion_log_execution_id'), table_name='tb_database_provider_ingestion_log')
    op.drop_column('tb_database_provider_ingestion_log', 'execution_id')
    op.drop_index(op.f('ix_tb_database_provider_ingestion_execution_triggered_by_id'), table_name='tb_database_provider_ingestion_execution')
    op.drop_index(op.f('ix_tb_database_provider_ingestion_execution_ingestion_id'), table_name='tb_database_provider_ingestion_execution')
    op.drop_table('tb_database_provider_ingestion_execution')
    # ### end Alembic commands ###
